# Generated by Django 5.1 on 2024-08-08 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdailyreward',
            name='is_referral_reward',
            field=models.BooleanField(default=False),
        ),
    ]
